name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run Ruff
        run: |
          uv run ruff check --output-format=github .
          uv run ruff format --check --output-format=github .
      - name: Run mamushi
        # Submodules are not installed by here => will be skipped
        run: uv run mamushi --line-length 100 contracts/ tests/
